name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Build macros
        run: cargo build --verbose --features macros
      - name: Build full
        run: cargo build --verbose --features full
      - name: Test
        run: cargo test --verbose --features full
      - name: Doc
        run: cargo doc --verbose --features full
