name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Build tokio-stream
        run: cargo build --verbose --features tokio-stream
      - name: Build full
        run: cargo build --verbose --features full
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests tokio-stream
        run: cargo test --verbose --features tokio-stream
      - name: Run tests full
        run: cargo test --verbose --features full
      - name: Run doc
        run: cargo doc --verbose --features full
